# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYMQXmqaJt9krOkIDepDLElWLrdfgCjJ
"""

import pandas as pd
spamcsv = pd.read_csv("/content/spam (1).csv", encoding="latin1")
spamdf = pd.DataFrame(spamcsv)
spamdf

def spamdetect(df, column):
  lst = []
  for j, v in df[column].items():
    if v == 'spam':
      lst.append((j, v))
    else:
        lst.append((j, v))
  print(lst)
spamdetect(spamdf, "v1")

